spring:
  datasource:
    url: localhost:3306/career_plan?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: ${PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    career:
      plan:
        service: debug
        controller: debug
        consumer: debug
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    default-executor-type: batch